name: Ngrok SSH Tunnel

on:
  workflow_dispatch:  # Allows you to start the tunnel manually

jobs:
  ngrok-tunnel:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Start Ngrok Tunnel for SSH
        uses: tmshkr/ngrok-ssh@latest
        with:
          NGROK_AUTHTOKEN: ${{ secrets.NGROK_AUTHTOKEN }}
          # If you want to supply a custom SSH public key:
          # SSH_PUBLIC_KEY: ${{ secrets.SSH_PUBLIC_KEY }}
          # The action waits until a connection is established:
          WAIT_FOR_CONNECTION: 'true'

      - name: Keep Tunnel Open
        # This step ensures the job remains active to keep the tunnel open.
        run: sleep 3600
